services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: studentapp-client
    ports:
      - "3000:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: studentapp-server
    ports:
      - "5000:8080"